# Generated by Django 2.2.6 on 2019-10-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroventa',
            name='empresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
