# Generated by Django 2.2.6 on 2019-10-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventaproducto',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='no_comprobante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='registroventaproducto',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registroventaproducto',
            name='no_comprobante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroventaproducto',
            name='producto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroventaproducto',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
