# Generated by Django 2.2.6 on 2019-10-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redneuronalresultados',
            name='clasificacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='empresa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='tipo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio',
            field=models.CharField(max_length=200),
        ),
    ]
