# Generated by Django 2.2.6 on 2019-10-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0002_auto_20191013_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroventaproducto',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
