# Generated by Django 2.2.6 on 2019-10-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0003_auto_20191013_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedNeuronalResultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('pema', models.FloatField(blank=True, null=True)),
                ('dam', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('look_back', models.IntegerField(blank=True, null=True)),
                ('neuronas', models.IntegerField(blank=True, null=True)),
                ('epocas', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
