# Generated by Django 2.2.6 on 2019-10-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0004_redneuronalresultados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redneuronalresultados',
            name='periodo',
            field=models.CharField(blank=True, choices=[('DIAS', 'DIAS'), ('MESES', 'MESES'), ('AÑOS', 'AÑOS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='redneuronalresultados',
            name='tipo',
            field=models.CharField(blank=True, choices=[('VENTAS', 'VENTAS'), ('PRODUCTOS', 'PRODUCTOS')], max_length=50, null=True),
        ),
    ]
