# Generated by Django 2.2.6 on 2019-10-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0006_auto_20191015_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='redneuronalresultados',
            name='dam_dir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redneuronalresultados',
            name='eval_dir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redneuronalresultados',
            name='pred_dir',
            field=models.TextField(blank=True, null=True),
        ),
    ]
