# Generated by Django 2.2.6 on 2019-10-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0007_auto_20191016_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ASESORIA Y SEGURIDAD EMPRESARIAL', 'ASESORIA Y SEGURIDAD EMPRESARIAL'), ('MONITOREO OCUPACIONAL', 'MONITOREO OCUPACIONAL'), ('INDEMINICACION POR PERDIDA DE BIENES ', 'INDEMINICACION POR PERDIDA DE BIENES '), ('MONITOREO AMBIENTAL ', 'MONITOREO AMBIENTAL '), ('AUDITORIA Y EVALUACION', 'AUDITORIA Y EVALUACION')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registroventaproducto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ASESORIA Y SEGURIDAD EMPRESARIAL', 'ASESORIA Y SEGURIDAD EMPRESARIAL'), ('MONITOREO OCUPACIONAL', 'MONITOREO OCUPACIONAL'), ('INDEMINICACION POR PERDIDA DE BIENES ', 'INDEMINICACION POR PERDIDA DE BIENES '), ('MONITOREO AMBIENTAL ', 'MONITOREO AMBIENTAL '), ('AUDITORIA Y EVALUACION', 'AUDITORIA Y EVALUACION')], max_length=50, null=True),
        ),
    ]
