# Generated by Django 2.2.6 on 2019-10-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0008_auto_20191016_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='redneuronalresultados',
            name='pema_dir',
            field=models.TextField(blank=True, null=True),
        ),
    ]
