# Generated by Django 2.2.6 on 2019-10-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0009_redneuronalresultados_pema_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50)),
            ],
        ),
    ]
