# Generated by Django 2.2.6 on 2019-10-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0010_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='redneuronalresultados',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('PRECIOS', 'PRECIOS'), ('DESCRIPCION', 'DESCRIPCION')], max_length=50, null=True),
        ),
    ]
