# Generated by Django 2.2.6 on 2019-10-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0012_auto_20191021_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='redneuronalresultados',
            name='rmse_dir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redneuronalresultados',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('AUDITORIA', 'AUDITORIA'), ('MONITOREO DE HIGIENE OCUPACIONAL', 'MONITOREO DE HIGIENE OCUPACIONAL'), ('CAPACITACION', 'CAPACITACION'), ('IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN ', 'IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN '), ('IPER Y MAPA DE RIESGOS', 'IPER Y MAPA DE RIESGOS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('AUDITORIA', 'AUDITORIA'), ('MONITOREO DE HIGIENE OCUPACIONAL', 'MONITOREO DE HIGIENE OCUPACIONAL'), ('CAPACITACION', 'CAPACITACION'), ('IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN ', 'IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN '), ('IPER Y MAPA DE RIESGOS', 'IPER Y MAPA DE RIESGOS')], max_length=50, null=True),
        ),
    ]
