# Generated by Django 2.2.6 on 2019-10-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0013_auto_20191021_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroventa',
            name='no_comprobante',
        ),
    ]
