# Generated by Django 2.2.6 on 2019-10-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0014_remove_registroventa_no_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redneuronalresultados',
            name='epocas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='redneuronalresultados',
            name='look_back',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='redneuronalresultados',
            name='neuronas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='redneuronalresultados',
            name='periodo',
            field=models.CharField(choices=[('DIAS', 'DIAS'), ('SEMANAS', 'SEMANAS'), ('MESES', 'MESES')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='empresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='ruc',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='tipo',
            field=models.CharField(choices=[('AUDITORIA', 'AUDITORIA'), ('MONITOREO DE HIGIENE OCUPACIONAL', 'MONITOREO DE HIGIENE OCUPACIONAL'), ('CAPACITACION', 'CAPACITACION'), ('IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN ', 'IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN '), ('IPER Y MAPA DE RIESGOS', 'IPER Y MAPA DE RIESGOS')], max_length=50),
        ),
    ]
