# Generated by Django 2.2.6 on 2019-10-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0015_auto_20191021_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVentaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('empresa', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=11)),
                ('precio', models.FloatField()),
                ('tipo', models.CharField(choices=[('AUDITORIA', 'AUDITORIA'), ('MONITOREO DE HIGIENE OCUPACIONAL', 'MONITOREO DE HIGIENE OCUPACIONAL'), ('CAPACITACION', 'CAPACITACION'), ('IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN ', 'IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN '), ('IPER Y MAPA DE RIESGOS', 'IPER Y MAPA DE RIESGOS'), ('GENERAL', 'GENERAL')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='redneuronalresultados',
            name='clasificacion',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('IPER Y MAPA DE RIESGOS', 'IPER Y MAPA DE RIESGOS'), ('IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN ', 'IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN '), ('CAPACITACION', 'CAPACITACION'), ('MONITOREO DE HIGIENE OCUPACIONAL', 'MONITOREO DE HIGIENE OCUPACIONAL'), ('AUDITORIA', 'AUDITORIA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='tipo',
            field=models.CharField(choices=[('AUDITORIA', 'AUDITORIA'), ('MONITOREO DE HIGIENE OCUPACIONAL', 'MONITOREO DE HIGIENE OCUPACIONAL'), ('CAPACITACION', 'CAPACITACION'), ('IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN ', 'IMPLEMENTACIÓN DE SISTEMAS DE GESTIÓN '), ('IPER Y MAPA DE RIESGOS', 'IPER Y MAPA DE RIESGOS'), ('GENERAL', 'GENERAL')], max_length=50),
        ),
    ]
